language: node_js
node_js: node
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_81f9259c944f_key -iv $encrypted_81f9259c944f_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
install:
  - npm install
  - npm run build
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: sherwinyu-215103
  default: true
  on:
    all_branches: true
