language: node_js
node_js: node
branches:
  only:
    - master
before_install:
  # [START auth]
  # Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
  - openssl aes-256-cbc -K $encrypted_81f9259c944f_key -iv $encrypted_81f9259c944f_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  # If the SDK is not already cached, download it and unpack it
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
    curl https://sdk.cloud.google.com | bash;
    fi
  - tar -xzf credentials.tar.gz
  # Here we use the decrypted service account credentials to authenticate the command line tool
  - gcloud auth activate-service-account --key-file client-secret.json
install:
  - npm install
  - npm run build
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: sherwinyu-215103
  default: true
  on:
    all_branches: true
