language: node_js
node_js: node

branches:
  only:
    - master

install:
  # Install the app's dependencies
  - npm install
  - npm run build
  - curl -L  $SECRET_FILE > secrets.json

deploy:
  provider: gae
  # Skip cleanup so api_key.py and vendored dependencies are still there
  skip_cleanup: true
  keyfile: secrets.json
  project: sherwinyu-215103
  default: true
  on:
    all_branches: true
# script:
#   # Build and bundle for production
#   - npm run build
#   # curl for secret file
#   - curl -L  $SECRET_FILE > secrets.json
#   # login to gcloud
#   - gcloud auth activate-service-account --key-file secrets.json
#   # deploy
#   - gcloud app deploy
