name: gcloud
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true
  
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup gcloud environment
        uses: GoogleCloudPlatform/github-actions@0.1.1
        with:
          # The version of the gcloud SDK to be installed.  Example: 275.0.0
          version: '278.0.0'
          # The service account email which will be used for authentication.
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          # The service account key which will be used for authentication.
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
      - run: ls
      - run: gcloud app deploy ~/website/app.yaml
